---
title: "Modelo ingreso"
output: html_document
---

```{r, error=FALSE, warning=FALSE, message=FALSE, echo=FALSE, eval=TRUE}
library(tidyverse)
library(rstan)
rm(list = ls())
ruta_trabajo <- setwd('C:/Users/H11765/Documents/Proyecto/modelo_ingreso')
```

## Datos a nivel hogar
```{r, error=FALSE, warning=FALSE, message=FALSE, echo=TRUE, eval=TRUE}
base_ingreso_hog <- read_csv('base_ingreso.csv')
```

```{r, error=FALSE, warning=FALSE, message=FALSE, echo=TRUE, eval=TRUE}
# selección de conjunto de entrenamiento y prueba general
set.seed(1234)
muestra <- round(nrow(base_ingreso_hog) * 0.80, 0)
ind <- sample(c(1:nrow(base_ingreso_hog)), muestra)
datos_entre_hog <- base_ingreso_hog[ind, ]
datos_prueba_hog <- base_ingreso_hog[-ind, ]
rm('muestra', 'ind')
```

```{r, error=FALSE, warning=FALSE, message=FALSE, echo=FALSE, eval=FALSE}
# selección de conjunto de entrenamiento y prueba considerando muestra de todas las entidades
set.seed(1234)
base_ingreso_hog$entidad <- as.numeric(substr(base_ingreso_hog$ubica_geo, 1, 2))
for(i in 1:32){
  entidad <- filter(base_ingreso_hog, entidad == i)
  muestra <- round(nrow(entidad) * 0.80, 0)
  set.seed(1234)
  ind <- sample(c(1:nrow(entidad)), muestra)
  if (i == 1){
    datos1_entre_hog <- entidad[ind, ]
    datos1_prueba_hog <- entidad[-ind, ]
  }
  else{
      datos1_entre_hog <- rbind(datos1_entre_hog, entidad[ind, ])
      datos1_prueba_hog <- rbind(datos1_prueba_hog, entidad[-ind, ])
  }
}
rm('entidad', 'muestra', 'i', 'ind')
```

```{r, error=FALSE, warning=FALSE, message=FALSE, echo=TRUE, eval=TRUE}
x_hogar_entre <- model.matrix(~ - 1 + tenen + drenaje_1 + elect_1 + combus + eli_ba_1 + 
                              cua_coc_1 + excus_1 + vehi_1 + serv_comu_n + act_mayvalor_n + 
                              act_normal_n + equipa_n + cuart_n + tam_hog_n + hab_cuar_prom + 
                              hombres_n + mujeres_n + menores_n + p12_64_n + p65mas_n + 
                              ocup_n + pering_n + donativo_1 + remesas_1 + bene_gob_1 + 
                              j_sexo + j_edad + j_ed_formal + max_nved_h + hablaind_n + 
                              alfabe_n + ic_asalud_n + rezedu_may16_n + ins_ali_h + ic_cv_h + 
                              ic_sbv_h + rel_depen + tasa_mort + j_ocup + j_rezedu + 
                              j_hablaind + j_disc + j_ind + j_sub + j_sermed + 
                              j_agui + j_vac + j_utili + j_afore + j_sect + 
                              cony_sexo + cony_edad + cony_ed_formal + cony_ocup + cony_rezedu + 
                              cony_hablaind + cony_disc + cony_ind + cony_sub + cony_sermed + 
                              cony_agui + cony_vac + cony_utili + cony_afore + cony_sect + 
                              p16_menos_trab_n + p16_64_trab_n + p65mas_trab_n + jub_pen_n + tam_loc, 
                              data = datos_entre_hog)

x_hogar_prueba <- model.matrix(~ - 1 + tenen + drenaje_1 + elect_1 + combus + eli_ba_1 + 
                              cua_coc_1 + excus_1 + vehi_1 + serv_comu_n + act_mayvalor_n + 
                              act_normal_n + equipa_n + cuart_n + tam_hog_n + hab_cuar_prom + 
                              hombres_n + mujeres_n + menores_n + p12_64_n + p65mas_n + 
                              ocup_n + pering_n + donativo_1 + remesas_1 + bene_gob_1 + 
                              j_sexo + j_edad + j_ed_formal + max_nved_h + hablaind_n + 
                              alfabe_n + ic_asalud_n + rezedu_may16_n + ins_ali_h + ic_cv_h + 
                              ic_sbv_h + rel_depen + tasa_mort + j_ocup + j_rezedu + 
                              j_hablaind + j_disc + j_ind + j_sub + j_sermed + 
                              j_agui + j_vac + j_utili + j_afore + j_sect + 
                              cony_sexo + cony_edad + cony_ed_formal + cony_ocup + cony_rezedu + 
                              cony_hablaind + cony_disc + cony_ind + cony_sub + cony_sermed + 
                              cony_agui + cony_vac + cony_utili + cony_afore + cony_sect + 
                              p16_menos_trab_n + p16_64_trab_n + p65mas_trab_n + jub_pen_n + tam_loc, 
                              data = datos_prueba_hog)
```

```{r, error=FALSE, warning=FALSE, message=FALSE, echo=FALSE, eval=FALSE}
x1_hogar_entre <- model.matrix(~ - 1 + tenen + drenaje_1 + elect_1 + combus + eli_ba_1 + 
                              cua_coc_1 + excus_1 + vehi_1 + serv_comu_n + act_mayvalor_n + 
                              act_normal_n + equipa_n + cuart_n + tam_hog_n + hab_cuar_prom + 
                              hombres_n + mujeres_n + menores_n + p12_64_n + p65mas_n + 
                              ocup_n + pering_n + donativo_1 + remesas_1 + bene_gob_1 + 
                              j_sexo + j_edad + j_ed_formal + max_nved_h + hablaind_n + 
                              alfabe_n + ic_asalud_n + rezedu_may16_n + ins_ali_h + ic_cv_h + 
                              ic_sbv_h + rel_depen + tasa_mort + j_ocup + j_rezedu + 
                              j_hablaind + j_disc + j_ind + j_sub + j_sermed + 
                              j_agui + j_vac + j_utili + j_afore + j_sect + 
                              cony_sexo + cony_edad + cony_ed_formal + cony_ocup + cony_rezedu + 
                              cony_hablaind + cony_disc + cony_ind + cony_sub + cony_sermed + 
                              cony_agui + cony_vac + cony_utili + cony_afore + cony_sect + 
                              p16_menos_trab_n + p16_64_trab_n + p65mas_trab_n + jub_pen_n + tam_loc, 
                              data = datos1_entre_hog)

x1_hogar_prueba <- model.matrix(~ - 1 + tenen + drenaje_1 + elect_1 + combus + eli_ba_1 + 
                                cua_coc_1 + excus_1 + vehi_1 + serv_comu_n + act_mayvalor_n + 
                                act_normal_n + equipa_n + cuart_n + tam_hog_n + hab_cuar_prom + 
                                hombres_n + mujeres_n + menores_n + p12_64_n + p65mas_n + 
                                ocup_n + pering_n + donativo_1 + remesas_1 + bene_gob_1 + 
                                j_sexo + j_edad + j_ed_formal + max_nved_h + hablaind_n + 
                                alfabe_n + ic_asalud_n + rezedu_may16_n + ins_ali_h + ic_cv_h + 
                                ic_sbv_h + rel_depen + tasa_mort + j_ocup + j_rezedu + 
                                j_hablaind + j_disc + j_ind + j_sub + j_sermed + 
                                j_agui + j_vac + j_utili + j_afore + j_sect + 
                                cony_sexo + cony_edad + cony_ed_formal + cony_ocup + cony_rezedu + 
                                cony_hablaind + cony_disc + cony_ind + cony_sub + cony_sermed + 
                                cony_agui + cony_vac + cony_utili + cony_afore + cony_sect + 
                                p16_menos_trab_n + p16_64_trab_n + p65mas_trab_n + jub_pen_n + tam_loc, 
                                data = datos1_prueba_hog)
```
## Datos a nivel municipio
```{r, error=FALSE, warning=FALSE, message=FALSE, echo=TRUE, eval=TRUE}
base_ingreso_mun <- read_csv('base_municipio.csv')

base_ingreso_mun <- base_ingreso_mun %>%
                    select(ubica_geo, 
                           per_med, uni_med, tasa_alf, ind_agu, ind_dre,
                           ind_ele, ind_des_hum, per_doc, esc_edu, uni_eco,
                           conapo)

x_mun <- model.matrix(~ -1 + per_med + uni_med + tasa_alf + ind_agu + ind_dre+
                      ind_ele + ind_des_hum + per_doc + esc_edu + uni_eco + 
                      conapo,
                      data = base_ingreso_mun)
```
## Modelo
```{r, error=FALSE, warning=FALSE, message=FALSE, echo=TRUE, eval=TRUE}
ingreso <- datos_entre_hog$ingcor
geo_id <- as.numeric(factor(datos_entre_hog$ubica_geo))
datos_mod <- list(n = nrow(x_hogar_entre),
              n_mun = nrow(x_mun),
              mh = ncol(x_hogar_entre),
              mm = ncol(x_mun),
              ingreso = ingreso,
              x_hogar = x_hogar_entre,
              x_municipio = x_mun,
              municipio = geo_id)
```

```{r, error=FALSE, warning=FALSE, message=FALSE, echo=FALSE, eval=FALSE}
ingreso1 <- datos1_entre_hog$ingcor
geo_id <- as.numeric(factor(datos1_entre_hog$ubica_geo))
datos1_mod <- list(n = nrow(x1_hogar_entre),
              n_mun = nrow(x_mun),
              mh = ncol(x1_hogar_entre),
              mm = ncol(x_mun),
              ingreso = ingreso1,
              x_hogar = x1_hogar_entre,
              x_municipio = x_mun,
              municipio = geo_id)
```

```{r, error=FALSE, warning=FALSE, message=FALSE, echo=TRUE, eval=TRUE}
rstan_options(auto_write = TRUE)
options(mc.cores = parallel::detectCores())
mod_ingreso <- stan_model(file = 'mod_ingreso.stan')

fit <- sampling(mod_ingreso, data = datos_mod, iter = 2000, chains = 4)
print(fit, pars = c('beta_0', 'beta', 'alpha'), digits = 1)
```

```{r, error=FALSE, warning=FALSE, message=FALSE, echo=TRUE, eval=TRUE}
post <- as.matrix(fit)
colnames(post)[1:20]
sel <- grep('log_reps', colnames(post))

# intervalos de confianza
ci90 <- matrix(NA, nrow = length(sel), ncol = 2)
for (i in 1:length(sel)) {
    ci90[i,] <- quantile(post[,sel[i]], prob = c(0.05, 0.95), names = FALSE)
}

# gráfica
log_ingreso <- log(1 + ingreso)
plot(0, type= 'n', xlim = c(0,length(log_ingreso)), ylim = range(post[, sel]),
     xlab = 'hogar', ylab = 'ingreso', main = "")
t <- 1:nrow(datos_entre_hog)
polygon(c(rev(t), t), c(rev(ci90[,1]), ci90[,2]), col = '#FF668830', border = FALSE)
lines(1:nrow(datos_entre_hog), colMeans(post[,sel]), col = '#40D2FE', lwd = 2)
lines(log_ingreso, col = '#808080', lwd = 2)
legend('bottomright', c('series', "pred (avg)", 'pred (50% CI)', 'pred (90% CI)'),
       col = c('#808080', '#40D2FE', '#FF668880', '#FF668830'),
       lwd = c(2,2,2))
```

